{{- if .Values.service.enabled }}
{{- if eq .Values.service.type "LoadBalancer" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-kubernetes.fullname" . }}-{{ .Values.service.type | lower }}
  labels:
    {{- include "hello-kubernetes.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "hello-kubernetes.selectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}